version: 2
sources:
  - name: bronze
    catalog: main
    schema: bronze
    tables:
      - name: railway_stations
      - name: population_grid
      - name: stg_railway_stations
      - name: stg_population_grid
