name: dbt_next_station

profile: next_station

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt_project:
    +schema: raw

vars:
  h3_resolutions: [5, 6, 7, 8, 9, 10]

models:
  dbt_next_station:
    bronze:
      +materialized: table

    silver:
      +materialized: table

    gold:
      +materialized: table
