on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform -chdir=terraform/runtime fmt -check

      - name: Terraform Init
        run: terraform -chdir=terraform/runtime init

      - name: Terraform Validate
        run: terraform -chdir=terraform/runtime validate

      - name: Install build tools
        run: pip install build wheel

      - name: Build runtime infrastructure
        run: terraform -chdir=terraform/runtime apply -auto-approve

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Build python wheel
        run: python -m build --wheel

      - name: Deploy bundle
        run: databricks bundle deploy -t prod

      - name: Run bundle
        run: databricks bundle run -t prod

      - name: Destroy runtime infrastructure
        run: terraform -chdir=terraform/runtime destroy -auto-approve
