on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    env:
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4

      - name: Deploy infrastructure
        run: |
          terraform -chdir=terraform/core/infrastructure fmt -check
          terraform -chdir=terraform/core/infrastructure init
          terraform -chdir=terraform/core/infrastructure validate
          terraform -chdir=terraform/core/infrastructure apply -auto-approve

      - name: Deploy workspace
        run: |
          terraform -chdir=terraform/core/workspace fmt -check
          terraform -chdir=terraform/core/workspace init
          terraform -chdir=terraform/core/workspace validate
          terraform -chdir=terraform/core/workspace apply -auto-approve

      - name: Deploy workspace-resources
        run: |
          terraform -chdir=terraform/core/workspace-resources fmt -check
          terraform -chdir=terraform/core/workspace-resources init
          terraform -chdir=terraform/core/workspace-resources validate
          terraform -chdir=terraform/core/workspace-resources apply -auto-approve

      - name: Deploy runtime
        run: |
          terraform -chdir=terraform/runtime fmt -check
          terraform -chdir=terraform/runtime init
          terraform -chdir=terraform/runtime validate
          terraform -chdir=terraform/runtime apply -auto-approve

      - name: Export workspace variables
        run: |
          WORKSPACE_HOST="$(terraform -chdir=terraform/core/workspace output -raw workspace_url)"
          SQL_WAREHOUSE_ID="$(terraform -chdir=terraform/core/workspace-resources output -raw sql_warehouse_id)"

          echo "DATABRICKS_HOST=$WORKSPACE_HOST" >> "$GITHUB_ENV"
          echo "BUNDLE_VAR_sql_warehouse_id=$SQL_WAREHOUSE_ID" >> "$GITHUB_ENV"

      - name: Install build tools
        run: pip install build wheel

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Build python wheel
        run: python -m build --wheel

      - name: Deploy bundle
        run: databricks bundle deploy -t prod

      - name: Run bundle
        run: databricks bundle run -t prod

      - name: Destroy runtime infrastructure
        if: always()
        run: terraform -chdir=terraform/runtime destroy -auto-approve
